### ISSUE TITLE
Configure to use external libraries?

### ISSUE THREAD

**Issue by barracuda156** [oxen-io/oxen-libquic#25]
Now once we have `oxenc`, `oxen-logging` and `ngtcp2` in Macports, we would like to use those with `oxen-libquic` instead of building duplicates. Is it possible? (I mean, as a configure option, without heavy patching of CMakeLists.)

**Comment by dr7ana** [comment]
Thanks for making the first issue on this! Please let us know what you think of the library, what you use it for, etc

That's a great idea for a configurable option, I will add that to the dev to-do

**Comment by jagerman** [comment]
These are definitely things we want to do before this library goes into a release, both for Debian and other packaging systems.  (So yeah, we'll get to it before this library needs to be packaged for Lokinet use).

**Comment by dr7ana** [comment]
@barracuda156 your wish has been (finally) fulfilled with the pending libquic release

Closed with #84

**Comment by barracuda156** [comment]
@dr7ana Awesome! Will try building it.

**Comment by dr7ana** [comment]
@barracuda156 standby for another few days, this will be out with the libquic release :)
